---
matrix:
  include:
  -
    before_script:
    - "cd MockServer"
    jdk: openjdk8
    language: java
    script: "mvn clean package"
  -
    before_script:
    - "cd ContractService"
    jdk: openjdk8
    language: java
    script: "mvn clean package"
  -
    before_script:
    - "cd codegenerator"
    jdk: openjdk8
    language: java
    script: "mvn clean package"